---
all:
  children:
    web-servers:
      hosts: localhost
      vars:
        ansible_user: ubuntu
        ansible_python_interpreter: "/usr/bin/python3"
        ansible_ssh_private_key_file: "/keys/test-key.pem"
